name: Build Repository
on: [push]
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Packages
      run: msbuild Andraste.UILauncher.csproj /t:Restore
 
    - name: Build project
      run: msbuild Andraste.UILauncher.csproj /p:Configuration=Release /p:Platform=x86 /t:Build
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Release win-x86
        path: bin\Release\net48\*
